# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2M2RlODI0YThjY2Q2MzNlMWJkZGY4YSIsImlhdCI6MTcxNTMzMzE1Nn0.CiGox5LV88nBCBEhGPyko7tNY1SUWFetqZLzh-lzSJc
# POST http://localhost:3000/sign-up
# Content-Type: application/json

# {
#   "fullname": "john",
#   "email": "john2@example.com",
#   "password": "John@123"
# }

# POST http://localhost:3000/get-blog
# Content-Type: application/json

# {
#   "blog_id": "Ho-ng-Th-nh-Th-ng-Long-Minh-ch-ng-cho-s-ph-t-tri-n-c-a-n-n-v-n-minh-d-n-t-cpnT1ehpnK0j80SdBp8h5s"
# }

POST http://localhost:3000/get-profile
Content-Type: application/json

{
  "username": "phungkitai1810"
}
