POST http://localhost:3000/user-written-blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NjcxN2E4MmM1NjU1YjUzM2NjZjdlZSIsImlhdCI6MTcxOTYyODk3OX0.-2ROwI7y9vbznujFuaPIA-vd52BorCcVLU8B9VDFuD4
Content-Type: application/json

{
  "page": 1,
  "draft": false
}